# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Quartenia.github.io/tf2_gans/"

git_url = "https://github.com/Quartenia/tf2_gans/tree/master/"

def custom_doc_links(name): return None
