# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UpsampleConv2D": "blocks.ipynb",
         "DownBlock": "blocks.ipynb",
         "UpBlock": "blocks.ipynb",
         "ResBlock": "blocks.ipynb",
         "TrainerBase": "core.ipynb",
         "BCE_generator_loss": "losses.ipynb",
         "BCE_discriminator_loss": "losses.ipynb"}

modules = ["blocks.py",
           "core.py",
           "losses.py"]

doc_url = "https://Quartenia.github.io/tf2_gans/"

git_url = "https://github.com/Quartenia/tf2_gans/tree/master/"

def custom_doc_links(name): return None
