# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/losses.ipynb (unless otherwise specified).

__all__ = ['BCE_generator_loss', 'BCE_discriminator_loss']

# Cell
def BCE_generator_loss(y_pred):
    return tf.keras.losses.binary_crossentropy(tf.ones_like(y_pred), y_pred)

# Cell
def BCE_discriminator_loss(y_true, y_pred):
    real_loss = tf.keras.losses.binary_crossentropy(tf.ones_like(y_true),
                                                    y_true)
    fake_loss = tf.keras.losses.binary_crossentropy(tf.zeros_like(y_pred),
                                                    y_pred)
    return real_loss + fake_loss